version: "3.9"
services:
  kafka:
    image: vectorized/redpanda
    command: redpanda start --overprovisioned
    ports: ["9092:9092"]

  qdrant:
    image: qdrant/qdrant:v1.8
    ports: ["6333:6333"]

  ingest:
    build: ../services/ingest
    env_file: ../.env.example
    depends_on: [kafka]

  macro_agent:
    build: ../services/macro_agent
    env_file: ../.env.example
    depends_on: [kafka,qdrant]

  strategy_agent:
    build: ../services/strategy_agent
    env_file: ../.env.example
    depends_on: [kafka,qdrant]

  executor:
    build: ../services/executor
    env_file: ../.env.example
    depends_on: [kafka]

  api:
    build: ../services/api
    ports: ["8000:8000"]
    env_file: ../.env.example
    depends_on: [kafka]
